version: "3"

services:
  next-app-container:
    container_name: next-app-container
    build:
      context: .
      dockerfile: dockerfile.production
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
        PORT : ${PORT}
    restart: always
    ports:
      - 3000:3000

      
    # networks:
    #   - my_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true